#!/bin/bash

alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias apt-upgrade='sudo apt update && sudo apt upgrade'
alias ascii-code='man 7 ascii'
alias caps-to-ctrl='setxkbmap -option ctrl:nocaps'
alias cgrep='grep --color=always'
alias clip='xclip -selection clipboard'
alias j='jobs'
alias o='xdg-open'
alias reload-aliases='source ~/.bash_aliases'
alias s='autossh'
alias sshfs-close='fusermount -uz'
alias swap-reset='sudo swapoff -a && sudo swapon -a'
alias t='tig --all'
alias v='less'
alias wget='wget --show-progress'
alias xev='xev | sed -n 's/^ *\(.*keycode.*\), same_screen.*$/\1/p''
alias xkb-output='xkbcomp $DISPLAY -'
alias xkb-print='setxkbmap -print'
