#!/bin/bash

alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias apt-depends='apt-cache-recurse depends'
alias apt-rdepends='apt-cache-recurse rdepends'
alias apt-upgrade='sudo apt update && sudo apt upgrade'
alias asciicode='man 7 ascii'
alias caps-to-ctrl='setxkbmap -option ctrl:nocaps'
alias cgrep='grep --color=always'
alias e='spacemacs-client -cn'
alias j='jobs'
alias o='xdg-open'
alias p='background evince'
alias reload-aliases='source ~/.bash_aliases'
alias reload-shell='exec $SHELL'
alias s='autossh'
alias swap-reset='sudo swapoff -a && sudo swapon -a'
alias t='tig --all'
alias v='less'
alias wget='wget --show-progress'
alias xev="xev | sed -n 's/^ *\(.*keycode.*\), same_screen.*$/\1/p'"
